# Generated by Django 5.1.6 on 2025-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="watch_history",
        ),
        migrations.AddField(
            model_name="customuser",
            name="watch_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
