# Generated by Django 5.1.6 on 2025-03-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_customuser_bio_customuser_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferences',
        ),
    ]
