# Generated by Django 5.1.6 on 2025-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_customuser_is_email_verified_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_genres',
            field=models.ManyToManyField(related_name='favorite_users', to='movies.genre'),
        ),
    ]
