# Generated by Django 5.1.6 on 2025-04-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_customuser_favorite_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='watch_history',
        ),
    ]
