# Generated by Django 5.1.6 on 2025-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_created_at_remove_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reviewed_movies',
            field=models.ManyToManyField(blank=True, related_name='reviewed_users', to='movies.movie'),
        ),
    ]
